### ISSUE TITLE
3.8.1 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#182]
## Features
- [x] #133 
- [x] translation updates (Spanish, Ukrainian, Romanian, Armenian)
- [x] add new community themes https://github.com/sannybuilder/themes
- [x] data files update https://github.com/sannybuilder/data/pull/22
  - [x] new GTA SA PS2 edit mode https://github.com/sannybuilder/data/pull/24
- [x] update local CHM help https://github.com/MatiDragon-YT/help-system
- [x] update CLEO
  - [x] [CLEO 4.4.1](https://github.com/cleolibrary/CLEO4/releases/tag/v4.4.1)
  - [x] [CLEO for GTA III and Vice City v2.0.0.6](https://github.com/cleolibrary/III.VC.CLEO/releases/tag/2.0.0.6)
  - [x] [CLEO+ 1.1.2](https://github.com/JuniorDjjr/CLEOPlus/releases/tag/v1.1.2)

## Bug Fixes
- [x] #172 
- [x] #189

**Comment by x87** [comment]
https://github.com/sannybuilder/dev/releases/tag/v3.8.1-beta.0

v3.8.1 is available for public testing! Please report any issues found in this version here or on Discord.
https://discord.gg/d5dZSfgBZr

**Comment by MatiDragon-YT** [comment]
@x87 was released [CLEO+ 1.1.2](https://github.com/JuniorDjjr/CLEOPlus/releases/tag/v1.1.2)

**Comment by x87** [comment]
beta.1 is available
https://github.com/sannybuilder/dev/releases/tag/v3.8.1-beta.1

[Direct link to download](https://github.com/sannybuilder/dev/releases/download/v3.8.1-beta.1/SannyBuilder-v3.8.1-beta.1.exe)
