### ISSUE TITLE
VCS Support

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#2]
As a user I should be able to compile a script into the VCS SCM Format.

Community Specification: 
* https://gtamods.com/wiki/LCS/VCS_SCM
* https://gtamods.com/wiki/Opcode#Data_types

**Comment by x87** [comment]
### TODO:
- [ ] custom opcodes (if, jf, start_mission)
- [ ] opcode-less expressions
- [ ] long strings (0x0A)
- [ ] unlock compiler menu
