### ISSUE TITLE
3.8.3 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#211]
## Bug Fixes
- [x] #210 
- [x] #204 
- [x] #168 
- [x] https://github.com/sannybuilder/GetObjectID/issues/1 

## Updates
- [x] update CLEO+ to [1.1.3](https://github.com/JuniorDjjr/CLEOPlus/releases/tag/v1.1.3)
- [x] data files update https://github.com/sannybuilder/data/pull/26
