### ISSUE TITLE
3.8.4 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#215]
## Features
- [x] #151 
- [x] #214 

## Bug Fixes

- [x] #212 
- [x] #213
- [x] fix some compilation issues with classes using string literals
  - [x] https://github.com/sannybuilder/dev/issues/66#issuecomment-683345731
  - [x] https://github.com/sannybuilder/dev/issues/66#issuecomment-715513873
- [x] #180
