### ISSUE TITLE
3.9.0 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#231]
## Breaking Changes

Some old code may not compile in this version. Read through the notes [down below](https://github.com/sannybuilder/dev/issues/231#issuecomment-1627984136).

## Download
https://github.com/sannybuilder/dev/releases/tag/v3.9.0

## Features
- [x] command names defined in SBL JSON files are now valid keywords (available in GTA III, VC, SA modes)
- [x] #230 
  - [x] new `byte(n)` syntax
  - [x] $include adds the file as a binary blob
  - [x] [documentation](https://docs.sannybuilder.com/coding/hex..end#byte-repetition)
- [x] inline [const](https://docs.sannybuilder.com/coding/constants#syntax) and [var](https://docs.sannybuilder.com/coding/variables#declaring-a-variable-type) declarations
  - [x] `const x = 1`
  - [x] `var $x: int`
  - [x] comma-separated declarations `const x = 1, y = 2`, `var $x:int, $z: array 10 of int`, `int x, y = 1, z = 3`
  - [x] language service update
  - [x] documentation on inline [constants](https://docs.sannybuilder.com/coding/constants#syntax), [variables](https://docs.sannybuilder.com/coding/variables#declaring-a-variable-type), and [arrays](https://docs.sannybuilder.com/coding/arrays#array-declaration)
 - [x] new operators
   - [x] #97
   - [x] #115
   - [x] #116 
   - [x] [documentation](https://docs.sannybuilder.com/coding/operators)
- [x] #134
- [x] #220 
- [x] #244
- [x] `{$USE}` directive accepts multiple comma-separated extensions
- [x] #196 
  - [x] documentation
- [x] #74 
  - [x] #68 
  - [x] [documentation](https://docs.sannybuilder.com/edit-modes)
- [x] the compiler now throws an error on a duplicate constant declaration
  - [x] document new [error code 0090](https://docs.sannybuilder.com/troubleshooting/errors/0090)
- [x] the default [Case converting](https://docs.sannybuilder.com/editor/options/formats#case-converting) option for new installations is now "As is"
- [x] third-party updates
  - [x] CLEO 4.4.4 https://github.com/cleolibrary/CLEO4
  - [x] CLEO+ 1.1.5 https://github.com/JuniorDjjr/CLEOPlus
  - [x] help 1.18 https://github.com/MatiDragon-YT/help-system/releases/tag/1.18
 - [x] translation updates https://github.com/sannybuilder/translations/pull/22
 - [x] opcode updates https://github.com/sannybuilder/data/pull/27

## Bug Fixes
- [x] #212 
- [x] #223 
- [x] #152 
- [x] #219 
- [x] #190
- [x] #240 
- [x] #245 
- [x] #246 
  - [x] document new [error code 0091](https://docs.sannybuilder.com/troubleshooting/errors/0091)
- [x] #247 
- [x] https://github.com/sannybuilder/core/issues/12
- [x] https://github.com/sannybuilder/core/issues/14
- [x] update list of objects after opening a new file with another edit mode (#233)

**Comment by x87** [comment]
Inner changes

- new, stricter INI parser. helped to identify some mistakes in the existing files. OLD *SCM.INI won't work and likely cause compilation errors.
- split of the `modes.xml` into individual files. Sanny scans \data directory for folders with `mode.xml` and treats them as modes.
- split of the monolithic `SASCM.INI` into multiple INI files. Adding extra opcodes is as easy as just dropping a file named `SASCM.*.ini` into the `data\sa` folder

**Comment by x87** [comment]
## Breaking Changes

- compiler now throws an error if an unknown* model name is used in a FOR loop range, or inside a HEX..END.

i.e. the following code is no longer valid. 
```
for 0@ = #MODEL1 to #MODEL100 
```
```
hex
 #MODEL1
end
```


> *Unknown model is such a model, that is not defined in the standard IDE files such as `default.ide`, `peds.ide`, or `vehicles.ide`. Or the game directory is not set in the options, so the compiler can't read those files.

Previously the compiler would try to add those modes to the DEFINE OBJECT list if it was an SCM file (not CLEO) and replaced model names with negative indexes in that list, e.g. -1 or -2. This behavior most likely deviates from the script goal and leads to many confusions. 

To compile this code, the compiler should have access to the game's data folder, meaning one should [set the game directory](https://docs.sannybuilder.com/editor/options/general#game-directory) in the options. Then, it scans the standard IDE files (see above) and finds an id for the given models (MODEL1 and MODEL100). If such names are not found, another error is thrown.

Alternative path is to replace model names in the code with their respective IDs (numbers).

**Comment by x87** [comment]
## Release Notes

1. it is now possible to generate a series of repetitive bytes in hex..end using new byte(N) syntax. For example, if you needed 10 zero bytes, you had to write each one individually as follows:
```
hex
  00 00 00 00 00 00 00 00 00 00
end
```
Now it is possible to write:

```
hex
 00(10)
```

there should be no whitespace between a byte and a number of repetitions enclosed in braces. You can use this syntax many time in one block:

```
hex
  00(3) FF 01(4) FF
end
```
will be unwrapped to

```
hex
  00 00 00 FF 01 01 01 01 FF
end

```
