### ISSUE TITLE
3.4.0 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#30]
This issue documents features and fixes planned for the next release:

- [x] VCS compiler support #2 
- [x] callable gosubs (incl. highlighting and auto-complete)
- [x] shorter form of local variable declaration (#32 )
- [x] GXT entry in games.xml #7 
- [x] opcodes.txt entry in games.xml #5 
- [x] online documentation link
- [x] Ctrl+Alt+H label in options #22 sannybuilder/translations/issues/2
- [x] minor opcode description updates (player money +=, award_achievement, 0479 in VCS)
- [x] new cleo script from menu
- [x] templates per edit mode #39 
- [x] ZAZ tutorial #24 
- [x] Run Game for GTASA should check gta-sa.exe (Steam)
- [x] Revert GXT text files #25

**Comment by wmysterio** [comment]
Привет! Может добавить в CLEO или вшить прямо в SB опкод:
```if
Condition
jt @label // XXXX: jump_if_true @label

//...
@label```

Думаю, что это будет лакомым куском :)

**Comment by x87** [comment]
> Привет! Может добавить в CLEO или вшить прямо в SB опкод:
> 
> ```
> if
> Condition
> jt @label // XXXX: jump_if_true @label
> 
> //...
> :label
> ```
> 
> Думаю, что это будет лакомым куском :)

I think you can just invert Condition to achieve the same:

if 
   not Condition
jf @label

// ...
:label
```

**Comment by wmysterio** [comment]
Я в курсе об этом. Хотелось бы сделать код немного гибче, как это сделал опкод `0AA1`. Вроде как мелочь, а своё применение нашел. А `jump_if_true`, думаю, можно применять чаще и без лишних танцев с инверсией (это не сложно, но можно ведь проще).

**Comment by x87** [comment]
I think `jump_if_true` could be implemented as a CLEO plugin.

callable gosubs are a shorter form of

```
gosub @proc
```

```
proc()
```

**Comment by wmysterio** [comment]
В CLEO было столько разработчиков, что уже не поймёшь к кому обращаться. 13AG, если не ошибаюсь, уже месяцами не отвечает на сообщения (может не со всеми так). Попросил бы добавить этот опкод, но бог его знает где он )

Идею "callable gosubs" понял. Ждём релиз ;)

Я пока справку поковыряю, скину тибе перевод для онайн-документации. Как раз появилось свободное время.

**Comment by x87** [comment]
Released 08/04/20
