### ISSUE TITLE
3.5.0 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#47]
https://github.com/sannybuilder/dev/milestone/1

- update CLI
  - [x] new syntax with dashes #42 
  - [x] new parameters `-x`, `--game`, `--mode` #42
  - [x] modes hot reloading #15
- edit modes enhancements
  - [x] `games.xml` renamed to `modes.xml`, inner names changed too (`<games>` -> `<modes>`)
  - [x] modes can inherit properties of other modes (useful for different versions of one game)
  - [x] new mode for SA 2.0 (with CustomLabels_v2.ini)
  - [x] separate modes for different versions of VCS #41 
  - [x] support for custom IDE/DAT files
    - [x] mitigate the difference in file referencing in game DAT and custom.dat #18 
  - [x] increase space for mode name section #8 
- LCS/VCS support
  - [x] fix LCS and VCS compilation #49 
  - [x] fix discrepancy in CustomLabels.ini offsets in LCS/VCS #52 
  - [x] enable constant_indexes debug option for LCS/VCS by default
  - [x] update LCS/VCS with fastman92 opcode definitions https://github.com/sannybuilder/data/pull/5
- [x] fix file association https://github.com/sannybuilder/dev/issues/43#issuecomment-670219723
- [x] remove SAMB->SB converter #27 
- [x] can't open Opcode Search Tool again after minimize #35 
- [x] update documentation on CLI and modes

**Comment by wmysterio** [comment]
"Ini path" option have blank textbox always and button about him is not clickable. It necessary or it a bug?
