### ISSUE TITLE
3.6.0 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#61]
- [x] new classes.db parser
  - [x] support for multiple enum params in one class
  - [x] Access violation at address 0057DBDB in module 'sanny.exe'. ??? #62 [0047](http://bugs.sannybuilder.com/view.php?id=47)
- [x] enums support (only in classes)
  - [x] enums.txt #20 
    - [x] implement some enums from https://github.com/sannybuilder/dev/issues/75#issuecomment-698684393
  - [x] enums entry in modes.xml
  - [x] support for named enums in classes.db
    - [x] convert "extended" params to named enums
    - [x] deprecate "extended" params
    - [x] compiler-only support for deprecated "extended" params
  - [x] autocomplete support for named enums
  - [x] [documentation](https://docs.sannybuilder.com/coding/classes#class-constants)
- [x] support for [TEXT_LABEL32](https://gtamods.com/wiki/SCM_language#TEXT_LABEL32) -  in SA and SA_Mobile only
  - [x] new %k data type #21 
  - [x] remove hardcoded handling of 05b6 (sa, sa_mobile), 0a66, 0a67, 0a68, 0a6e (sa_mobile) from disassembler - fixes #80
  - [x] backward compatibility for debug id in the compiler
  - [x] update https://docs.sannybuilder.com/troubleshooting/errors/0029
- [x] support for %m params #10 
  - [x] update [documentation](https://docs.sannybuilder.com/edit-modes/opcodes-list-scm.ini#opcode-parameters)
  - [x] update GTAMods.com wiki
- [x] use CLEO opcodes 0A9E, 0A9F, 0A90, 0A91 in certain expressions when no opcode is supplied https://github.com/sannybuilder/dev/issues/58#issuecomment-723376464 
- [x] Recognize Cleo for Android Scripts as Compiled Scripts #64 
  - [x] update all translations  
  - [x] update [documentation](https://docs.sannybuilder.com/options/general#file-association)
- [x] initial support for language extensions in edit modes #74
  - [x] hardcode list of opcodes and extensions - extensions.txt https://github.com/sannybuilder/data/pull/6
  - [x] compiler throws an error on missing $use directive
  - [x] disassembler restores $use directive
  - [x] throw ERR_0089 on missing extension
  - [x] documentation
- [x] update CLEO to [v4.4](https://github.com/cleolibrary/CLEO4/releases)
  - [x] include [CLEO+](https://github.com/JuniorDjjr/CLEOPlus/releases) #71 (+sascm.ini, opcodes.txt)
  - [x] update SCRLog  https://github.com/cleolibrary/CLEO4/issues/31
  - [x] keywords for CLEO opcodes in gta3, vc, sa modes
- [x] game directory is optional #48 
   - [x] needed for model id resolving (GetObjectID) -> throws [0083](https://docs.sannybuilder.com/troubleshooting/errors/0083)
   - [x] make a note in 0083 on missing game directory
- [x] configurable copy directory #9 #48 
- [x] remove opcodes ini section from options #51 
- [x] update Spanish and Italian translation https://github.com/sannybuilder/translations/pull/7 #63 
- [x] update templates for SCR modes #70 
- [x] add keywords in GTA SA SCR mode
- [x] update opcodes https://github.com/sannybuilder/data/pull/6
  - [x] update all definitions to replace `thread`->`script` [See GTAMods.com](https://gtamods.com/wiki/Talk:Script#Thread-&gt;Script)
- [x] fix #83 #84
