### ISSUE TITLE
3.7.0 Release Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#90]
## Features

- [x] Each editor tab maintains its own edit mode selection #87 
  - [x] investigate memory leak when selecting different modes in the same tab 
- [x] Highlight constants #28 
  - [x] language service https://github.com/sannybuilder/core/pull/4
  - [x] translation update https://github.com/sannybuilder/translations/pull/9
  - [x] documentation on language service & new highlighting options
 - [x] Autocomplete list should display constants anywhere #40 
- [x] edit modes update https://github.com/sannybuilder/data/pull/11
  - [x] new VC Mobile mode
    - [x] improve models list loading when there are a lot of IDE files
  - [x] Added @spaceeinstein's Opcode Restoration project opcodes in VC PC mode
  - [x] Updated GTA III's SCM.INI to include all missing opcodes
- [x] Switch to the new make_opcodes #14 
- [x] Error message should have a link to localized documentation if possible #101 
- [x] User tools should support sb and game path variables #72 
  - [x] update https://docs.sannybuilder.com/features#external-tools-menu
- [x] Update CLEO+ 
  - [x] v1.0.7 https://github.com/JuniorDjjr/CLEOPlus/releases
- [x] Bottom panel updates
  - [x] bottom panel displays the current status of the language service for the opened file (Disabled, Ready, Scanning).
  - [x] bottom panel displays the constant value in the when the cursor is on its name
  - [x] bottom panel better handles available space during window resize
- [x] Data type keywords (int, float, string, etc) are now highlighted

## Bug Fixes

- [x] Fixed an issue when label cannot be decompiled correctly #103
- [x] Fixed high-level code limitation #114
- [x] Model Id corrupted when duplicated in 2dfx section of IDE file #120
- [x] In GTA3, VC, SA disassembler now always assume the label value is integer regardless of data type
- [x] Type of parameters in opcode 0237 in GTA3 changed back to a number, not model id (regression in 3.6.0)
- [x] Disassembler now correctly writes `cleo_return` word before the arguments of opcode 0AB2
- [x] Compilation error for class `Actor.Create` when argument for pedtype param is deprecated enum value ("extended param")
- [x] Fixed an issue when the `gosub` command was disassembled into a function even with "Write opcodes" enabled
- [x] Fixed an issue when a subroutine (e.g. `MyLabel()`) can not be compiled in GTA SA SCR mode (reported [here](https://gtaforums.com/topic/211077-rel-sanny-builder/page/26/?tab=comments#comment-1071457506))

## Breaking Changes
* `constants.txt` in edit modes are converted from a dictionary to the source file implicitly included during compilation. On practice it should not affect users but if you are using modified `constants.txt` you will need to wrap the content of this file in `const..end`:

Before 3.7.0

```
false=0
true=1
TIMERA=32@
TIMERB=33@
```

After 3.7.0

```
const
false=0
true=1
TIMERA=32@
TIMERB=33@
end
```

* Variable `@sb:\` used in modes.xml has been replaced with `@sb:` to better handle cases where the trailing slash is not needed.

**Comment by x87** [comment]
v3.7.0-alpha.0 is available for preview:
https://github.com/sannybuilder/dev/releases

By no means this is feature complete and it doesn't include all planned changes. But this is the way for me to get early feedback and fine-tune things before the release. Please comment 👍

**Comment by x87** [comment]
Observation #1: changing `constants.txt` to an implicit include file broke the SCM file header compilation. Compiler assumes DEFINE lines to be the very first.

**Comment by x87** [comment]
v3.7.0-alpha.3 is available for preview
https://github.com/sannybuilder/dev/releases/download/v3.7.0-alpha.3/SannyBuilder-v3.7.0-alpha.3.exe

New features: https://github.com/sannybuilder/dev/releases/tag/v3.7.0-alpha.3

**Comment by XMDS** [comment]
@x87 Currently switching from other modes to VC Mobile mode, there will be a delayed unresponsive state, wait for a period of time to switch to this mode normally, and use this mode to create new text and write cleo, there will still be unresponsive delays.  In addition.  You seem to forget to add the gxt file of VCM.

There should be a bug. In the SB setting, the label format setting and the case conversion setting seem to be unable to coexist. When setting either case conversion, we will not be able to choose to set the label format.  You can take a look

**Comment by XMDS** [comment]
@x87  2 suggestions:
1.We should set "write opcodes" as the default setting, so that the player can correctly display the standard OP description syntax when decompiling

2.Gosub still displays the abbreviated label () when "write opcodes" is decompiled. This problem has been reported by many people.

**Comment by x87** [comment]
> You seem to forget to add the gxt file of VCM.

there was no GXT file in https://github.com/sannybuilder/data/pull/11 which I just merged as is. I don't think I have this file. If you can open another PR with this file I'm happy to add that in.

>When setting either case conversion, we will not be able to choose to set the label format.

great catch! I will look into it

**Comment by x87** [comment]
>switching from other modes to VC Mobile mode, there will be a delayed unresponsive state,

I noticed that too. I think it happens as Sanny scans ide files to get a list of models for autocomplete. If we had one single file with all models it would load much faster.

**Comment by XMDS** [comment]
> > You seem to forget to add the gxt file of VCM.
> 
> there was no GXT file in [sannybuilder/data#11](https://github.com/sannybuilder/data/pull/11) which I just merged as is. I don't think I have this file. If you can open another PR with this file I'm happy to add that in.
> 

In this branch, in my second reply, there is a zip file download. Although it is an old file, it contains a gxt file, which you can add to the sb directory.  In addition, it also has two different sizes of icons for the VC mobile version, which you can use as icons for sb's VCM mode

https://github.com/sannybuilder/data/pull/11

**Comment by x87** [comment]
Can you uploads it again? says 404

**Comment by XMDS** [comment]
> Can you upload it again? says 404

https://github.com/XMDS/GTA.III.VC.SA.CDK/releases/tag/untagged-717e7e8efd5c95fc126b

**Comment by x87** [comment]
404 not found. It might be a private release file that only owners of that repo can see.

**Comment by XMDS** [comment]
> 404 not found. It might be a private release file that only owners of that repo can see.
https://mega.nz/file/Uf4CDbrZ

**Comment by XMDS** [comment]
Can you accept the file now
https://mega.nz/file/Uf4CDbrZ#Qo2gZ2zNG0ePq5NQYFv_6GDGCjkcImmYY8pYhRjTi_w

**Comment by x87** [comment]
Yes I downloaded it, thanks. Just removed those comments as they don't seem relevant.

**Comment by x87** [comment]
>In the SB setting, the label format setting and the case conversion setting seem to be unable to coexist. 

>Gosub still displays the abbreviated label () when "write opcodes" is decompiled. This problem has been reported by many people.

fixed in alpha.4
https://github.com/sannybuilder/dev/releases/download/v3.7.0-alpha.4/SannyBuilder-v3.7.0-alpha.4.exe

**Comment by x87** [comment]
>Currently switching from other modes to VC Mobile mode, there will be a delayed unresponsive state

this has been addressed in beta.0
https://github.com/sannybuilder/dev/releases/download/v3.7.0-beta.0/SannyBuilder-v3.7.0-beta.0.exe

list of changes: https://github.com/sannybuilder/dev/releases/tag/v3.7.0-beta.0

**Comment by XMDS** [comment]
@x87  Constant highlighting is no longer valid in beta0.0 version

**Comment by x87** [comment]
@XMDS thank you for reporting. not sure how I missed this.

here is the fix: place attached `core.dll` to `Sanny Builder\lib` folder.
[core.dll.zip](https://github.com/sannybuilder/dev/files/5864462/core.dll.zip)
