### ISSUE TITLE
3.6.1 Update Plan

### ISSUE THREAD

**Issue by x87** [sannybuilder/dev#91]
- [x] update Ukrainian language https://github.com/sannybuilder/translations/pull/8 (by @wmysterio)
- [x] opening `.csa` extension does not invoke disassembler #88 
- [x] autocomplete for directives does not list `{$USE}`
- [x] autocomplete for directives does not work after compilation
- [x] disassembler prints a non-existent label #81 
- [x] if `settings.ini` has `Lang=2057`, the translation from `english.ini` is not used
- [x] Exception in Number to Model Conversion #94 
- [x] in Number to Model Conversion ignore model names not starting with a letter (fixes https://github.com/sannybuilder/GetObjectID/issues/1)
- [x] update data files  #95 https://github.com/sannybuilder/data/pull/8
  - [x] GTA3, VC: merge `CLEO1.1` into `CLEO`
  - [x] add missing bitwise opcodes `0B17`-`0B1D`
  - [x] SA Mobile: merge `ios` extension into `default`
  - [x] remove opcodes disabled in NewOpcodes 2.0
 - [x] Regression: Keywords search is now case-sensitive #96 
 - [x] Regression: Compiler confuses scientific float notation with CLEO arithmetic command #98 
- [x] update CLEO+ to v1.0.4 https://github.com/JuniorDjjr/CLEOPlus/issues/1
